### ISSUE TITLE
Feedback Status-Page

### ISSUE THREAD

**Issue by WouterVanAssche** [vscentrum/status-page#1]
- Incident flagged as "planned: yes" does not appear under planned maintenance on the status page.
- Changing or adding 1 incident overwrites the "Updated" column for all existing incidents
- Clicking on the title of an incident to inspect the details shows the details for all existing incidents

**Comment by gjbex** [comment]
* a planned incident that is "current", i.e., past its start date will not be in the planned category.  Is this the case?
* The links bring you to the incidents, but if there a few incidents, it seems as if it points to all.
* I'll look into the update issue.

**Comment by WouterVanAssche** [comment]
> * a planned incident that is "current", i.e., past its start date will not be in the planned category.  Is this the case?

I will test further.

**Comment by WouterVanAssche** [comment]
> * a planned incident that is "current", i.e., past its start date will not be in the planned category.  Is this the case?
This works as intended. future incidents are shown under planned maintenance

**Comment by WouterVanAssche** [comment]
What factor determines the order in which incidents are displayed on the overview page (and detail view) ?

**Comment by WouterVanAssche** [comment]
Following incident.yml file ended up on the status page under planned maintenance, start_date was already in the past end_date was midnight.

```
meta_data:
  title: Lustre problems, scratch and staging experiencing delays
  start_date: 2022-06-21 16:30:00
  end_date: 2022-06-22 00:00:00
  affected: tier2_leuven
  level: high
  planned: no
content: >

  We are experiencing some delays on lustre (scratch and staging).

    * System is now recovered and responding, however as some scripts are still running

    * no new jobs will start on the system.

```
status page snapshot:
![image](https://user-images.githubusercontent.com/78903104/174831064-9a761927-c575-4f03-bbac-b23005ded8ea.png)
