### ISSUE TITLE
Non planned appears as planned

### ISSUE THREAD

**Issue by wpoely86** [vscentrum/status-page#17]
I've added a outage as:
```yaml
  title: VSC network unavailable
  start_date: 2022-11-18 09:37:00
  end_date:
  affected: backbone, tier2_brussels
  level: high
  planned: no
```

Yet it appears under 'planned'. I'm assuming the times are local time right?
